apiVersion: v1
kind: Pod
metadata:
  name: hostpath-vol-pod1
spec:
  containers:
   - name: test-container
     image: tomcat
     volumeMounts:
      - name: hostpath-volume
        mountPath: /tmp
  volumes:
   - name: hostpath-volume
     hostPath:
       path: /home/ubuntu     # directory location on host
       type: Directory  # this field is optional
