kind: Pod
apiVersion: v1
metadata:
   name: multicontainerpod
   labels:
     environment: dev
     app: ecomm
spec:
   containers:
      - name: c1
        image: ubuntu
        command: ["/bin/bash", "-c", "while true; do echo Hello-orange; sleep 5 ; done"]
      - name: c2
        image: ubuntu
        command: ["/bin/bash", "-c", "while true; do echo Hello-Banana; sleep 5 ; done"]
   restartPolicy: Never         # Defaults to Always
